# Generated by Django 3.0.3 on 2020-04-03 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='review_created_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='review_text',
            field=models.CharField(default='', max_length=10000),
        ),
    ]
