# Generated by Django 3.0.3 on 2020-03-31 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='auto_increment_id',
            field=models.AutoField(default=None, primary_key=True, serialize=False),
        ),
    ]
