# Generated by Django 3.0.3 on 2020-03-31 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_auto_20200331_0146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='auto_increment_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
